name: Automatic Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

permissions:
  actions: write
  attestations: write
  checks: write
  contents: write
  discussions: write
  id-token: write
  packages: write

jobs:
  candidate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: 'Publish Package'
        run: deno publish
